import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// ─────────────────────────────────────────────
// Helper utilities
// ─────────────────────────────────────────────

const parseDate = (val) => {
  if (!val || val.trim() === "") return null;
  const d = new Date(val.trim());
  return isNaN(d.getTime()) ? null : d;
};

const parseDecimal = (val) => {
  if (val === null || val === undefined) return null;
  const num = parseFloat(val);
  return isNaN(num) ? null : num;
};

const parseString = (val) => {
  if (val === null || val === undefined || String(val).trim() === "") return null;
  return String(val).trim();
};

const parseIntVal = (val) => {
  if (val === null || val === undefined) return null;
  const num = parseInt(val, 10);
  return isNaN(num) ? null : num;
};

// ─────────────────────────────────────────────
// Electrical inventory data
// ─────────────────────────────────────────────

const electricalData = [
  {
    name: "2.5MM COPPER CABLE",
    itemCode: null,
    subItems: [
      {
        variant: "36MTR",
        dop: "2024-12-12",
        billNumber: null,
        quantity: "36MTR",
        unitRate: 93.0,
        amount: 3348.0,
        receivedQty: null,
        openingStock: null,
        issued: "0.0",
        balance: null,
        avlStockTotal: null,
        dealerName: "M/S MAHESH ENTERPRISES BERAGARH TCP TEKANPUR GWALIOR",
        slp: null,
        remarks: null,
      },
      {
        variant: "200MTR(2-100MTR)",
        dop: "2024-12-19",
        billNumber: null,
        quantity: "200MTR(2-100MTR)",
        unitRate: 14500.0,
        amount: 29000.0,
        receivedQty: null,
        openingStock: null,
        issued: "0.0",
        balance: null,
        avlStockTotal: null,
        dealerName: null,
        slp: null,
        remarks: null,
      },
      {
        variant: "100MTR",
        dop: "2025-01-01",
        billNumber: null,
        quantity: "100MTR",
        unitRate: 14500.0,
        amount: 14500.0,
        receivedQty: null,
        openingStock: null,
        issued: "0.0",
        balance: null,
        avlStockTotal: null,
        dealerName: null,
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "16 AMP SOCKET(CONA)",
    itemCode: null,
    subItems: [
      {
        variant: "50",
        dop: "2024-12-19",
        billNumber: null,
        quantity: "50",
        unitRate: 100.0,
        amount: 5000.0,
        receivedQty: "50.0",
        openingStock: "50.0",
        issued: "0.0",
        balance: "50.0",
        avlStockTotal: "50.0",
        dealerName: "M/S MAHESH ENTERPRISES TCP BAIRAGARH TEKANPUR GWAKIOR MP",
        slp: null,
        remarks: null,
      },
      {
        variant: "20",
        dop: "2024-12-28",
        billNumber: null,
        quantity: "20",
        unitRate: 100.0,
        amount: 2000.0,
        receivedQty: "20.0",
        openingStock: "20.0",
        issued: "0.0",
        balance: "20.0",
        avlStockTotal: "20.0",
        dealerName: "M/S SHEETLA ELECTRICALS INFRONT CENTRAL BOI",
        slp: null,
        remarks: null,
      },
      {
        variant: "16",
        dop: "2025-12-10",
        billNumber: null,
        quantity: "16",
        unitRate: 120.0,
        amount: 1920.0,
        receivedQty: "16.0",
        openingStock: "16.0",
        issued: null,
        balance: "0.0",
        avlStockTotal: "0.0",
        dealerName: "M/S SHRI KRISHNA COMPUTER ,SHUBHASH GANJ DABRA",
        slp: null,
        remarks: null,
      },
      {
        variant: "5",
        dop: "2026-04-10",
        billNumber: null,
        quantity: "5",
        unitRate: 110.0,
        amount: 550.0,
        receivedQty: "5.0",
        openingStock: "5.0",
        issued: null,
        balance: "0.0",
        avlStockTotal: "0.0",
        dealerName: "M/S NARMADA ENTERPRISES ,SHOP NO B11 RAJGERI APARTMENT GANDHI NAGAR GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "PEDESTRAL FAN 400MM TORPEDO",
    itemCode: null,
    subItems: [
      {
        variant: "4",
        dop: "2026-03-24",
        billNumber: null,
        quantity: "4",
        unitRate: 3280.0,
        amount: 13120.0,
        receivedQty: "4.0",
        openingStock: "4.0",
        issued: null,
        balance: "3.0",
        avlStockTotal: "3.0",
        dealerName: "M/S NARMADA ENTERPRISES ,SHOP NO B11 RAJGERI APARTMENT GANDHI NAGAR GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "6/16 AMP TWIN SOCKET WITH SHUTTER",
    itemCode: null,
    subItems: [
      {
        variant: "14",
        dop: "2026-04-09",
        billNumber: null,
        quantity: "14",
        unitRate: 89.56,
        amount: 1253.84,
        receivedQty: "14.0",
        openingStock: "14.0",
        issued: null,
        balance: "0.0",
        avlStockTotal: "0.0",
        dealerName: "JSB INDIA 32 TALWAR KA BADA OLD INDUSTRIAL AREA, TANSEN NAGAR ROAD GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "6AMP SWITCH -CONA",
    itemCode: null,
    subItems: [
      {
        variant: "50",
        dop: "2024-12-19",
        billNumber: null,
        quantity: "50",
        unitRate: 22.5,
        amount: 1125.0,
        receivedQty: "50.0",
        openingStock: "50.0",
        issued: "0.0",
        balance: "50.0",
        avlStockTotal: "50.0",
        dealerName: "M/S MAHESH ENTERPRISES BERAGARH TCP TEKANPUR GWALIOR",
        slp: null,
        remarks: null,
      },
      {
        variant: "100",
        dop: "2025-01-01",
        billNumber: null,
        quantity: "100",
        unitRate: 19.0,
        amount: 1900.0,
        receivedQty: "100.0",
        openingStock: "100.0",
        issued: "0.0",
        balance: "100.0",
        avlStockTotal: "100.0",
        dealerName: "M/S MAHESH ENTERPRISES BERAGARH TCP TEKANPUR GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "6AMP SWITCH -LEGRAND",
    itemCode: null,
    subItems: [
      {
        variant: "20",
        dop: "2025-11-20",
        billNumber: null,
        quantity: "20",
        unitRate: 61.36,
        amount: 1227.2,
        receivedQty: "20.0",
        openingStock: "20.0",
        issued: "0.0",
        balance: "20.0",
        avlStockTotal: "20.0",
        dealerName: "JSB INDIA 32 TALWAR KA BADA OLD INDUSTRIAL AREA, TANSEN NAGAR ROAD GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "10 AMP SWITCH",
    itemCode: null,
    subItems: [
      {
        variant: "50",
        dop: "2026-04-09",
        billNumber: null,
        quantity: "50",
        unitRate: 18.17,
        amount: 908.6,
        receivedQty: "50.0",
        openingStock: "50.0",
        issued: null,
        balance: "0.0",
        avlStockTotal: "0.0",
        dealerName: null,
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "6 amp socket -cona",
    itemCode: null,
    subItems: [
      {
        variant: "50",
        dop: "2024-12-19",
        billNumber: null,
        quantity: "50",
        unitRate: 38.0,
        amount: 1900.0,
        receivedQty: "50.0",
        openingStock: "50.0",
        issued: "0.0",
        balance: "50.0",
        avlStockTotal: "50.0",
        dealerName: "M/S MAHESH ENTERPRISES BERAGARH TCP TEKANPUR GWALIOR",
        slp: null,
        remarks: null,
      },
      {
        variant: "20",
        dop: "2024-12-28",
        billNumber: null,
        quantity: "20",
        unitRate: 50.0,
        amount: 1000.0,
        receivedQty: "20.0",
        openingStock: "20.0",
        issued: "0.0",
        balance: "20.0",
        avlStockTotal: "20.0",
        dealerName: "M/S JAI SHEETLA ELECTRICALS TEKANPUR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "6 AMP SOCKET - ANCHOR",
    itemCode: null,
    subItems: [
      {
        variant: "100",
        dop: "2025-01-01",
        billNumber: null,
        quantity: "100",
        unitRate: 30.0,
        amount: 3000.0,
        receivedQty: "100.0",
        openingStock: "100.0",
        issued: "0.0",
        balance: "100.0",
        avlStockTotal: "100.0",
        dealerName: "M/S MAHESH ENTERPRISES BERAGARH TCP TEKANPUR GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "6 AMP SOCKET LEGRAND",
    itemCode: null,
    subItems: [
      {
        variant: "20",
        dop: "2025-11-20",
        billNumber: null,
        quantity: "20",
        unitRate: 159.3,
        amount: 3186.0,
        receivedQty: "20.0",
        openingStock: "20.0",
        issued: "0.0",
        balance: "20.0",
        avlStockTotal: "20.0",
        dealerName: "JSB INDIA 32 TALWAR KA BADA OLD INDUSTRIAL AREA, TANSEN NAGAR ROAD GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "10AMP SOCKET SPIN AND SHUTTER",
    itemCode: null,
    subItems: [
      {
        variant: "6",
        dop: "2026-04-09",
        billNumber: null,
        quantity: "6",
        unitRate: 40.12,
        amount: 240.72,
        receivedQty: "6.0",
        openingStock: "6.0",
        issued: "6.0",
        balance: "0.0",
        avlStockTotal: "0.0",
        dealerName: "JSB INDIA 32 TALWAR KA BADA OLD INDUSTRIAL AREA, TANSEN NAGAR ROAD GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "16 AMP SWITCH",
    itemCode: null,
    subItems: [
      {
        variant: "50",
        dop: "2024-12-19",
        billNumber: null,
        quantity: "50",
        unitRate: 85.0,
        amount: 4250.0,
        receivedQty: "50.0",
        openingStock: "50.0",
        issued: "0.0",
        balance: "50.0",
        avlStockTotal: "50.0",
        dealerName: "M/S MAHESH ENTERPRISES BERAGARH TCP TEKANPUR GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "16 AMP SWITCH CONA",
    itemCode: null,
    subItems: [
      {
        variant: "5",
        dop: "2026-04-10",
        billNumber: null,
        quantity: "5",
        unitRate: 80.0,
        amount: 400.0,
        receivedQty: "5.0",
        openingStock: "5.0",
        issued: "5.0",
        balance: "0.0",
        avlStockTotal: "0.0",
        dealerName: "M/S NARMADA ENTERPRISES ,SHOP NO B11 RAJGERI APARTMENT GANDHI NAGAR GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "SWITCH 20A ONE WAY",
    itemCode: null,
    subItems: [
      {
        variant: "14",
        dop: "2026-04-09",
        billNumber: null,
        quantity: "14",
        unitRate: 45.65,
        amount: 639.1,
        receivedQty: "14.0",
        openingStock: "14.0",
        issued: null,
        balance: "0.0",
        avlStockTotal: "0.0",
        dealerName: "M/S JSB INDIA 32,TALWAR KA BADA OLD INDUSTRIAL AREA TANSEN NAGAR ROAD GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "CABLE CLIP",
    itemCode: null,
    subItems: [
      {
        variant: "10 PKT",
        dop: "2024-12-19",
        billNumber: null,
        quantity: "10 PKT",
        unitRate: 110.0,
        amount: 1100.0,
        receivedQty: null,
        openingStock: null,
        issued: "0.0",
        balance: null,
        avlStockTotal: null,
        dealerName: "M/S MAHESH ENTERPRISES BERAGARH TCP TEKANPUR GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "EXHAUST FAN 18''",
    itemCode: null,
    subItems: [
      {
        variant: "4",
        dop: "2026-03-24",
        billNumber: null,
        quantity: "4",
        unitRate: 4450.0,
        amount: 17800.0,
        receivedQty: "4.0",
        openingStock: "4.0",
        issued: null,
        balance: "1.0",
        avlStockTotal: "1.0",
        dealerName: "M/S NARMADA ENTERPRISES ,SHOP NO B11 RAJGERI APARTMENT GANDHI NAGAR GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "CLIP 25 SQ MM",
    itemCode: null,
    subItems: [
      {
        variant: "10PKT",
        dop: "2026-04-09",
        billNumber: null,
        quantity: "10PKT",
        unitRate: 41.3,
        amount: 413.0,
        receivedQty: null,
        openingStock: null,
        issued: null,
        balance: "0.0",
        avlStockTotal: "0.0",
        dealerName: "JSB INDIA 32 TALWAR KA BADA OLD INDUSTRIAL AREA, TANSEN NAGAR ROAD GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "100 WATT STREET LIGHT",
    itemCode: null,
    subItems: [
      {
        variant: "5",
        dop: "2024-12-19",
        billNumber: null,
        quantity: "5",
        unitRate: 2832.0,
        amount: 14160.0,
        receivedQty: "5.0",
        openingStock: "5.0",
        issued: "0.0",
        balance: "5.0",
        avlStockTotal: "5.0",
        dealerName: "M/S JAI SHEETLA ELECTRICALS INFRONT OF CENTRAL BOI TEKANPUR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "MODULAR SHEET",
    itemCode: null,
    subItems: [
      {
        variant: "10",
        dop: "2024-12-28",
        billNumber: null,
        quantity: "10",
        unitRate: 120.0,
        amount: 1200.0,
        receivedQty: "10.0",
        openingStock: "10.0",
        issued: "0.0",
        balance: "10.0",
        avlStockTotal: "10.0",
        dealerName: "M/S JAI SHEETLA ELECTRICALS INFRONT OF CENTRAL BOI TEKANPUR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "8 WAY SURFACE BOX",
    itemCode: null,
    subItems: [
      {
        variant: "10",
        dop: "2024-12-28",
        billNumber: null,
        quantity: "10",
        unitRate: 90.0,
        amount: 900.0,
        receivedQty: "10.0",
        openingStock: "10.0",
        issued: "0.0",
        balance: "10.0",
        avlStockTotal: "10.0",
        dealerName: "M/S JAI SHEETLA ELECTRICALS INFRONT OF CENTRAL BOI TEKANPUR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "TUBELIGHT 20W ORIENT",
    itemCode: null,
    subItems: [
      {
        variant: "300",
        dop: "2025-01-01",
        billNumber: null,
        quantity: "300",
        unitRate: 225.0,
        amount: 67500.0,
        receivedQty: "300.0",
        openingStock: "300.0",
        issued: "0.0",
        balance: "300.0",
        avlStockTotal: "300.0",
        dealerName: "M/S MAHESH ENTERPRISES BERAGARH TCP TEKANPUR GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "LED LUMLINEN 20W HAVELLS",
    itemCode: null,
    subItems: [
      {
        variant: "60",
        dop: "2025-11-20",
        billNumber: null,
        quantity: "60",
        unitRate: 141.6,
        amount: 8496.0,
        receivedQty: "60.0",
        openingStock: "60.0",
        issued: "4.0",
        balance: "56.0",
        avlStockTotal: "56.0",
        dealerName: "JSB INDIA 32 TALWAR KA BADA OLD INDUSTRIAL AREA, TANSEN NAGAR ROAD GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "T/L BATTEN CROMPTON 20W",
    itemCode: null,
    subItems: [
      {
        variant: "30",
        dop: "2026-02-12",
        billNumber: null,
        quantity: "30",
        unitRate: 120.0,
        amount: 3600.0,
        receivedQty: "30.0",
        openingStock: "30.0",
        issued: "0.0",
        balance: "30.0",
        avlStockTotal: "30.0",
        dealerName: "M/S NARMADA ENTERPRISES ,SHOP NO B11 RAJGERI APARTMENT GANDHI NAGAR GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "LED BULB 9WATT",
    itemCode: null,
    subItems: [
      {
        variant: "200",
        dop: "2025-01-01",
        billNumber: null,
        quantity: "200",
        unitRate: 85.0,
        amount: 17000.0,
        receivedQty: "200.0",
        openingStock: "200.0",
        issued: "0.0",
        balance: "200.0",
        avlStockTotal: "200.0",
        dealerName: "M/S MAHESH ENTERPRISES TCP BAIRAGARH TEKANPUR GWAKIOR MP",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "2.5 MM WIRE",
    itemCode: null,
    subItems: [
      {
        variant: "450MTR",
        dop: "2025-01-01",
        billNumber: null,
        quantity: "450MTR",
        unitRate: 38.0,
        amount: 17100.0,
        receivedQty: null,
        openingStock: null,
        issued: "0.0",
        balance: null,
        avlStockTotal: null,
        dealerName: "M/S MAHESH ENTERPRISES TCP BAIRAGARH TEKANPUR GWAKIOR MP",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "1.5 MM WIRE",
    itemCode: null,
    subItems: [
      {
        variant: "450MTR",
        dop: "2025-01-01",
        billNumber: null,
        quantity: "450MTR",
        unitRate: 28.0,
        amount: 12600.0,
        receivedQty: null,
        openingStock: null,
        issued: "0.0",
        balance: null,
        avlStockTotal: null,
        dealerName: "M/S JAI SHEETLA ELECTRICALS INFRONT OF CENTRAL BOI TEKANPUR",
        slp: null,
        remarks: null,
      },
      {
        variant: "90MTR (4 BUNDLE)",
        dop: "2025-01-31",
        billNumber: null,
        quantity: "90MTR (4 BUNDLE)",
        unitRate: 2112.2,
        amount: 8448.8,
        receivedQty: null,
        openingStock: null,
        issued: "0.0",
        balance: null,
        avlStockTotal: null,
        dealerName: "M/S JAI SHEETLA ELECTRICALS INFRONT OF CENTRAL BOI TEKANPUR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "PVC PIPE 1",
    itemCode: null,
    subItems: [
      {
        variant: "200FEET",
        dop: "2025-01-01",
        billNumber: null,
        quantity: "200FEET",
        unitRate: 60.0,
        amount: 12000.0,
        receivedQty: null,
        openingStock: null,
        issued: "0.0",
        balance: null,
        avlStockTotal: null,
        dealerName: "M/S MAHESH ENTERPRISES TCP BAIRAGARH TEKANPUR GWAKIOR MP",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "PVC BEND 1",
    itemCode: null,
    subItems: [
      {
        variant: "12",
        dop: "2026-03-28",
        billNumber: null,
        quantity: "12",
        unitRate: 12.0,
        amount: 144.0,
        receivedQty: "12.0",
        openingStock: "12.0",
        issued: "12.0",
        balance: "0.0",
        avlStockTotal: "0.0",
        dealerName: "M/S NARMADA ENTERPRISES ,SHOP NO B11 RAJGERI APARTMENT GANDHI NAGAR GWALIOR",
        slp: null,
        remarks: null,
      },
      {
        variant: "24",
        dop: "2025-01-01",
        billNumber: null,
        quantity: "24",
        unitRate: 10.0,
        amount: 240.0,
        receivedQty: "24.0",
        openingStock: "24.0",
        issued: "0.0",
        balance: "24.0",
        avlStockTotal: "24.0",
        dealerName: "M/S MAHESH ENTERPRISES TCP BAIRAGARH TEKANPUR GWAKIOR MP",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "PVC TEE",
    itemCode: null,
    subItems: [
      {
        variant: "12",
        dop: "2025-01-01",
        billNumber: null,
        quantity: "12",
        unitRate: 10.0,
        amount: 120.0,
        receivedQty: "12.0",
        openingStock: "12.0",
        issued: "0.0",
        balance: "12.0",
        avlStockTotal: "12.0",
        dealerName: "M/S MAHESH ENTERPRISES TCP BAIRAGARH TEKANPUR GWAKIOR MP",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "UCLIP 1 FOR PVC PIPE FITTING",
    itemCode: null,
    subItems: [
      {
        variant: "1PKT",
        dop: "2025-01-01",
        billNumber: null,
        quantity: "1PKT",
        unitRate: 500.0,
        amount: 500.0,
        receivedQty: null,
        openingStock: null,
        issued: "0.0",
        balance: null,
        avlStockTotal: null,
        dealerName: "M/S MAHESH ENTERPRISES TCP BAIRAGARH TEKANPUR GWAKIOR MP",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "INSULATION TAPE ROLL",
    itemCode: null,
    subItems: [
      {
        variant: "100",
        dop: "2025-01-01",
        billNumber: null,
        quantity: "100",
        unitRate: 14.0,
        amount: 1400.0,
        receivedQty: "100.0",
        openingStock: "100.0",
        issued: "0.0",
        balance: "100.0",
        avlStockTotal: "100.0",
        dealerName: "M/S MAHESH ENTERPRISES TCP BAIRAGARH TEKANPUR GWAKIOR MP",
        slp: null,
        remarks: null,
      },
      {
        variant: "30",
        dop: "2025-11-20",
        billNumber: null,
        quantity: "30",
        unitRate: 11.8,
        amount: 354.0,
        receivedQty: "30.0",
        openingStock: "30.0",
        issued: "3.0",
        balance: "27.0",
        avlStockTotal: "27.0",
        dealerName: "JSB INDIA 32 TALWAR KA BADA OLD INDUSTRIAL AREA, TANSEN NAGAR ROAD GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "SHEET 5X5",
    itemCode: null,
    subItems: [
      {
        variant: "15",
        dop: "2025-01-01",
        billNumber: null,
        quantity: "15",
        unitRate: 18.0,
        amount: 270.0,
        receivedQty: "15.0",
        openingStock: "15.0",
        issued: "0.0",
        balance: "15.0",
        avlStockTotal: "15.0",
        dealerName: "M/S MAHESH ENTERPRISES TCP BAIRAGARH TEKANPUR GWAKIOR MP",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "SHEET 7X5",
    itemCode: null,
    subItems: [
      {
        variant: "20",
        dop: "2025-01-01",
        billNumber: null,
        quantity: "20",
        unitRate: 24.0,
        amount: 480.0,
        receivedQty: "20.0",
        openingStock: "20.0",
        issued: "0.0",
        balance: "20.0",
        avlStockTotal: "20.0",
        dealerName: "M/S MAHESH ENTERPRISES TCP BAIRAGARH TEKANPUR GWAKIOR MP",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "SQUARE LED 1X1 FEET PANEL",
    itemCode: null,
    subItems: [
      {
        variant: "25",
        dop: "2025-01-01",
        billNumber: null,
        quantity: "25",
        unitRate: 1327.0,
        amount: 33175.0,
        receivedQty: "25.0",
        openingStock: "25.0",
        issued: "0.0",
        balance: "25.0",
        avlStockTotal: "25.0",
        dealerName: "M/S MAHESH ENTERPRISES TCP BAIRAGARH TEKANPUR GWAKIOR MP",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "FAN CONDENSOR 2.25 UF",
    itemCode: null,
    subItems: [
      {
        variant: "100",
        dop: "2025-01-01",
        billNumber: null,
        quantity: "100",
        unitRate: 40.0,
        amount: 4000.0,
        receivedQty: "100.0",
        openingStock: "100.0",
        issued: "0.0",
        balance: "100.0",
        avlStockTotal: "100.0",
        dealerName: "M/S MAHESH ENTERPRISES TCP BAIRAGARH TEKANPUR GWAKIOR MP",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "FAN CONDENSOR 3.15 UF",
    itemCode: null,
    subItems: [
      {
        variant: "200",
        dop: "2025-01-01",
        billNumber: null,
        quantity: "200",
        unitRate: 50.0,
        amount: 10000.0,
        receivedQty: "200.0",
        openingStock: "200.0",
        issued: "0.0",
        balance: "200.0",
        avlStockTotal: "200.0",
        dealerName: "M/S MAHESH ENTERPRISES TCP BAIRAGARH TEKANPUR GWAKIOR MP",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "LED 200W ROOF LIGHTS",
    itemCode: null,
    subItems: [
      {
        variant: "5",
        dop: "2025-01-01",
        billNumber: null,
        quantity: "5",
        unitRate: 8500.0,
        amount: 42500.0,
        receivedQty: "5.0",
        openingStock: "5.0",
        issued: "0.0",
        balance: "5.0",
        avlStockTotal: "5.0",
        dealerName: "M/S MAHESH ENTERPRISES TCP BAIRAGARH TEKANPUR GWAKIOR MP",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "MACHINE OIL",
    itemCode: null,
    subItems: [
      {
        variant: "1LTR",
        dop: "2025-01-01",
        billNumber: null,
        quantity: "1LTR",
        unitRate: 200.0,
        amount: 200.0,
        receivedQty: null,
        openingStock: null,
        issued: "0.0",
        balance: null,
        avlStockTotal: null,
        dealerName: "M/S MAHESH ENTERPRISES TCP BAIRAGARH TEKANPUR GWAKIOR MP",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "OIL PRESSURE KUPPY",
    itemCode: null,
    subItems: [
      {
        variant: "1",
        dop: "2025-01-01",
        billNumber: null,
        quantity: "1",
        unitRate: 50.0,
        amount: 50.0,
        receivedQty: "1.0",
        openingStock: "1.0",
        issued: "0.0",
        balance: "1.0",
        avlStockTotal: "1.0",
        dealerName: "M/S MAHESH ENTERPRISES TCP BAIRAGARH TEKANPUR GWAKIOR MP",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "185MM LUGS(ALUMINIUM/COPPER)",
    itemCode: null,
    subItems: [
      {
        variant: "20",
        dop: "2025-01-01",
        billNumber: null,
        quantity: "20",
        unitRate: 85.0,
        amount: 1700.0,
        receivedQty: "20.0",
        openingStock: "20.0",
        issued: "0.0",
        balance: "20.0",
        avlStockTotal: "20.0",
        dealerName: "M/S MAHESH ENTERPRISES TCP BAIRAGARH TEKANPUR GWAKIOR MP",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "GATE LIGHT",
    itemCode: null,
    subItems: [
      {
        variant: "45",
        dop: "2025-01-31",
        billNumber: null,
        quantity: "45",
        unitRate: 737.5,
        amount: 33187.5,
        receivedQty: "45.0",
        openingStock: "45.0",
        issued: "0.0",
        balance: "45.0",
        avlStockTotal: "45.0",
        dealerName: "M/S JAI SHEETLA ELECTRICALS INFRONT OF CENTRAL BOI TEKANPUR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "LED 2X2 VENUS 36 WATT",
    itemCode: null,
    subItems: [
      {
        variant: "9",
        dop: "2025-11-20",
        billNumber: null,
        quantity: "9",
        unitRate: 1416.0,
        amount: 12744.0,
        receivedQty: "9.0",
        openingStock: "9.0",
        issued: null,
        balance: "5.0",
        avlStockTotal: "5.0",
        dealerName: "JSB INDIA 32 TALWAR KA BADA OLD INDUSTRIAL AREA, TANSEN NAGAR ROAD GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "MCB 16 AMP SINGLE POLE",
    itemCode: null,
    subItems: [
      {
        variant: "6",
        dop: "2025-11-20",
        billNumber: null,
        quantity: "6",
        unitRate: 110.0,
        amount: 660.0,
        receivedQty: "6.0",
        openingStock: "6.0",
        issued: "0.0",
        balance: "6.0",
        avlStockTotal: "6.0",
        dealerName: "JSB INDIA 32 TALWAR KA BADA OLD INDUSTRIAL AREA, TANSEN NAGAR ROAD GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "MCCB HAVELLS 32AMP",
    itemCode: null,
    subItems: [
      {
        variant: "6",
        dop: "2026-04-27",
        billNumber: null,
        quantity: "6",
        unitRate: 150.0,
        amount: 900.0,
        receivedQty: "6.0",
        openingStock: "6.0",
        issued: "0.0",
        balance: "6.0",
        avlStockTotal: "6.0",
        dealerName: "M/S NARMADA ENTERPRISES ,SHOP NO B11 RAJGERI APARTMENT GANDHI NAGAR GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "MCB 32AMP SINGLE POLE",
    itemCode: null,
    subItems: [
      {
        variant: "6",
        dop: "2025-11-20",
        billNumber: null,
        quantity: "6",
        unitRate: 129.8,
        amount: 778.8,
        receivedQty: "6.0",
        openingStock: "6.0",
        issued: "2.0",
        balance: "4.0",
        avlStockTotal: "4.0",
        dealerName: "JSB INDIA 32 TALWAR KA BADA OLD INDUSTRIAL AREA, TANSEN NAGAR ROAD GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "FAN C/F CROMPTON 1200MM",
    itemCode: null,
    subItems: [
      {
        variant: "20",
        dop: "2026-03-24",
        billNumber: null,
        quantity: "20",
        unitRate: 1600.0,
        amount: 32000.0,
        receivedQty: "20.0",
        openingStock: "20.0",
        issued: null,
        balance: "13.0",
        avlStockTotal: "13.0",
        dealerName: "M/S NARMADA ENTERPRISES ,SHOP NO B11 RAJGERI APARTMENT GANDHI NAGAR GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "MCB 32 AMP CONA",
    itemCode: null,
    subItems: [
      {
        variant: "1",
        dop: "2026-04-10",
        billNumber: null,
        quantity: "1",
        unitRate: 165.0,
        amount: 165.0,
        receivedQty: "1.0",
        openingStock: "1.0",
        issued: null,
        balance: "0.0",
        avlStockTotal: "0.0",
        dealerName: "M/S NARMADA ENTERPRISES ,SHOP NO B11 RAJGERI APARTMENT GANDHI NAGAR GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "MCB 32 AMP HAVELLS",
    itemCode: null,
    subItems: [
      {
        variant: "Default",
        dop: null,
        billNumber: null,
        quantity: null,
        unitRate: null,
        amount: null,
        receivedQty: null,
        openingStock: null,
        issued: null,
        balance: null,
        avlStockTotal: null,
        dealerName: null,
        slp: null,
        remarks: null,
      },
      {
        variant: "6",
        dop: "2026-04-27",
        billNumber: null,
        quantity: "6",
        unitRate: 150.0,
        amount: 900.0,
        receivedQty: "6.0",
        openingStock: "6.0",
        issued: "0.0",
        balance: "6.0",
        avlStockTotal: "6.0",
        dealerName: "M/S NARMADA ENTERPRISES ,SHOP NO B11 RAJGERI APARTMENT GANDHI NAGAR GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "FANCY ANGLE HOLDER",
    itemCode: null,
    subItems: [
      {
        variant: "25",
        dop: "2025-11-20",
        billNumber: null,
        quantity: "25",
        unitRate: 47.2,
        amount: 1180.0,
        receivedQty: "25.0",
        openingStock: "25.0",
        issued: "0.0",
        balance: "25.0",
        avlStockTotal: "25.0",
        dealerName: "JSB INDIA 32 TALWAR KA BADA OLD INDUSTRIAL AREA, TANSEN NAGAR ROAD GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "WIRE FRLS 1 SQMM 200 MTR GREEN",
    itemCode: null,
    subItems: [
      {
        variant: "200MTR-1QNT",
        dop: "2025-11-20",
        billNumber: null,
        quantity: "200MTR-1QNT",
        unitRate: 2987.76,
        amount: 2987.76,
        receivedQty: null,
        openingStock: null,
        issued: "0.0",
        balance: null,
        avlStockTotal: null,
        dealerName: "JSB INDIA 32 TALWAR KA BADA OLD INDUSTRIAL AREA, TANSEN NAGAR ROAD GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "LED BULB 15 WATT",
    itemCode: null,
    subItems: [
      {
        variant: "25",
        dop: "2025-11-20",
        billNumber: null,
        quantity: "25",
        unitRate: 123.9,
        amount: 3097.5,
        receivedQty: "25.0",
        openingStock: "25.0",
        issued: "0.0",
        balance: "25.0",
        avlStockTotal: "25.0",
        dealerName: "JSB INDIA 32 TALWAR KA BADA OLD INDUSTRIAL AREA, TANSEN NAGAR ROAD GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "TOP 16 AMP 3 PIN",
    itemCode: null,
    subItems: [
      {
        variant: "10",
        dop: "2025-11-20",
        billNumber: null,
        quantity: "10",
        unitRate: 76.7,
        amount: 767.0,
        receivedQty: "10.0",
        openingStock: "10.0",
        issued: "0.0",
        balance: "10.0",
        avlStockTotal: "10.0",
        dealerName: "JSB INDIA 32 TALWAR KA BADA OLD INDUSTRIAL AREA, TANSEN NAGAR ROAD GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "TOP 16 AMP (CONA)",
    itemCode: null,
    subItems: [
      {
        variant: "10",
        dop: "2026-04-27",
        billNumber: null,
        quantity: "10",
        unitRate: 95.0,
        amount: 950.0,
        receivedQty: "10.0",
        openingStock: "10.0",
        issued: "0.0",
        balance: "10.0",
        avlStockTotal: "10.0",
        dealerName: "M/S NARMADA ENTERPRISES ,SHOP NO B11 RAJGERI APARTMENT GANDHI NAGAR GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "DOL STARTER TWO PHASE",
    itemCode: null,
    subItems: [
      {
        variant: "1",
        dop: "2025-11-20",
        billNumber: null,
        quantity: "1",
        unitRate: 2065.0,
        amount: 2065.0,
        receivedQty: "1.0",
        openingStock: "1.0",
        issued: "0.0",
        balance: "1.0",
        avlStockTotal: "1.0",
        dealerName: "JSB INDIA 32 TALWAR KA BADA OLD INDUSTRIAL AREA, TANSEN NAGAR ROAD GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "8M COVER PLATE",
    itemCode: null,
    subItems: [
      {
        variant: "13",
        dop: "2026-04-09",
        billNumber: null,
        quantity: "13",
        unitRate: 107.085,
        amount: 1392.105,
        receivedQty: "13.0",
        openingStock: "13.0",
        issued: null,
        balance: "0.0",
        avlStockTotal: "0.0",
        dealerName: "JSB INDIA 32 TALWAR KA BADA OLD INDUSTRIAL AREA, TANSEN NAGAR ROAD GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "WIRE 1.5 SQMM BLUE 200MTR  FRLS",
    itemCode: null,
    subItems: [
      {
        variant: "200MTR(4)",
        dop: "2026-04-09",
        billNumber: null,
        quantity: "200MTR(4)",
        unitRate: 5310.0,
        amount: 21240.0,
        receivedQty: null,
        openingStock: null,
        issued: null,
        balance: "0.0",
        avlStockTotal: "0.0",
        dealerName: "JSB INDIA 32 TALWAR KA BADA OLD INDUSTRIAL AREA, TANSEN NAGAR ROAD GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "WIRE 2.5 SQMM RED 200MTR FRLS",
    itemCode: null,
    subItems: [
      {
        variant: "200MTR(3 COIL)",
        dop: "2026-04-09",
        billNumber: null,
        quantity: "200MTR(3 COIL)",
        unitRate: 8488.92,
        amount: 25466.76,
        receivedQty: null,
        openingStock: null,
        issued: null,
        balance: "0.0",
        avlStockTotal: "0.0",
        dealerName: "JSB INDIA 32 TALWAR KA BADA OLD INDUSTRIAL AREA, TANSEN NAGAR ROAD GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "SURFACE BOX 12M",
    itemCode: null,
    subItems: [
      {
        variant: "1",
        dop: "2026-04-10",
        billNumber: null,
        quantity: "1",
        unitRate: 140.0,
        amount: 140.0,
        receivedQty: "1.0",
        openingStock: "1.0",
        issued: null,
        balance: "0.0",
        avlStockTotal: "0.0",
        dealerName: "M/S NARMADA ENTERPRISES ,SHOP NO B11 RAJGERI APARTMENT GANDHI NAGAR GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "CASING PATTI 2''",
    itemCode: null,
    subItems: [
      {
        variant: "35",
        dop: "2026-04-10",
        billNumber: null,
        quantity: "35",
        unitRate: 133.0,
        amount: 4655.0,
        receivedQty: "35.0",
        openingStock: "35.0",
        issued: null,
        balance: "0.0",
        avlStockTotal: "0.0",
        dealerName: "M/S NARMADA ENTERPRISES ,SHOP NO B11 RAJGERI APARTMENT GANDHI NAGAR GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "PVC CASING 1.5MM",
    itemCode: null,
    subItems: [
      {
        variant: "30",
        dop: "2026-04-09",
        billNumber: null,
        quantity: "30",
        unitRate: 88.5,
        amount: 2655.0,
        receivedQty: "30.0",
        openingStock: "30.0",
        issued: null,
        balance: "0.0",
        avlStockTotal: "0.0",
        dealerName: "JSB INDIA 32 TALWAR KA BADA OLD INDUSTRIAL AREA, TANSEN NAGAR ROAD GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "GITTI PVC (RAWAL PLUG)",
    itemCode: null,
    subItems: [
      {
        variant: "Default",
        dop: null,
        billNumber: null,
        quantity: null,
        unitRate: null,
        amount: null,
        receivedQty: null,
        openingStock: null,
        issued: null,
        balance: null,
        avlStockTotal: null,
        dealerName: null,
        slp: null,
        remarks: null,
      },
      {
        variant: "5PKT",
        dop: "2026-04-10",
        billNumber: null,
        quantity: "5PKT",
        unitRate: 25.0,
        amount: 125.0,
        receivedQty: null,
        openingStock: null,
        issued: null,
        balance: "0.0",
        avlStockTotal: "0.0",
        dealerName: "M/S NARMADA ENTERPRISES ,SHOP NO B11 RAJGERI APARTMENT GANDHI NAGAR GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "CABLE 2 CORE ALUMINIUM (ICAB)",
    itemCode: null,
    subItems: [
      {
        variant: "150MTR",
        dop: "2026-04-17",
        billNumber: null,
        quantity: "150MTR",
        unitRate: 25.0,
        amount: 4200.0,
        receivedQty: null,
        openingStock: null,
        issued: null,
        balance: "0.0",
        avlStockTotal: "0.0",
        dealerName: "M/S NARMADA ENTERPRISES ,SHOP NO B11 RAJGERI APARTMENT GANDHI NAGAR GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "SHEET 12M",
    itemCode: null,
    subItems: [
      {
        variant: "1",
        dop: "2026-04-10",
        billNumber: null,
        quantity: "1",
        unitRate: 170.0,
        amount: 170.0,
        receivedQty: "1.0",
        openingStock: "1.0",
        issued: null,
        balance: "0.0",
        avlStockTotal: "0.0",
        dealerName: "M/S NARMADA ENTERPRISES ,SHOP NO B11 RAJGERI APARTMENT GANDHI NAGAR GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "BOX-3M",
    itemCode: null,
    subItems: [
      {
        variant: "1",
        dop: "2026-04-10",
        billNumber: null,
        quantity: "1",
        unitRate: 60.0,
        amount: 60.0,
        receivedQty: "1.0",
        openingStock: "1.0",
        issued: null,
        balance: "0.0",
        avlStockTotal: "0.0",
        dealerName: "M/S NARMADA ENTERPRISES ,SHOP NO B11 RAJGERI APARTMENT GANDHI NAGAR GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "WOODEN SCREW 1.5INCH",
    itemCode: null,
    subItems: [
      {
        variant: "5PKT",
        dop: "2026-04-10",
        billNumber: null,
        quantity: "5PKT",
        unitRate: 60.0,
        amount: 300.0,
        receivedQty: null,
        openingStock: null,
        issued: null,
        balance: "0.0",
        avlStockTotal: "0.0",
        dealerName: "M/S NARMADA ENTERPRISES ,SHOP NO B11 RAJGERI APARTMENT GANDHI NAGAR GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "CAPACITOR 50MFD HAVELLS",
    itemCode: null,
    subItems: [
      {
        variant: "1",
        dop: "2026-04-17",
        billNumber: null,
        quantity: "1",
        unitRate: 200.0,
        amount: 200.0,
        receivedQty: "1.0",
        openingStock: "1.0",
        issued: null,
        balance: "0.0",
        avlStockTotal: "0.0",
        dealerName: "M/S NARMADA ENTERPRISES ,SHOP NO B11 RAJGERI APARTMENT GANDHI NAGAR GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "STEEL NAIL 2''",
    itemCode: null,
    subItems: [
      {
        variant: "4",
        dop: "2026-04-10",
        billNumber: null,
        quantity: "4",
        unitRate: 10.0,
        amount: 40.0,
        receivedQty: "4.0",
        openingStock: "4.0",
        issued: "4.0",
        balance: "0.0",
        avlStockTotal: "0.0",
        dealerName: "M/S NARMADA ENTERPRISES ,SHOP NO B11 RAJGERI APARTMENT GANDHI NAGAR GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "STEEL NAIL 3''",
    itemCode: null,
    subItems: [
      {
        variant: "2",
        dop: null,
        billNumber: null,
        quantity: "2",
        unitRate: 20.0,
        amount: 40.0,
        receivedQty: "2.0",
        openingStock: "2.0",
        issued: "2.0",
        balance: "0.0",
        avlStockTotal: "0.0",
        dealerName: null,
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "SHEET 3M",
    itemCode: null,
    subItems: [
      {
        variant: "1",
        dop: "2026-04-10",
        billNumber: null,
        quantity: "1",
        unitRate: 70.0,
        amount: 70.0,
        receivedQty: "1.0",
        openingStock: "1.0",
        issued: null,
        balance: "0.0",
        avlStockTotal: "0.0",
        dealerName: "M/S NARMADA ENTERPRISES ,SHOP NO B11 RAJGERI APARTMENT GANDHI NAGAR GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
  {
    name: "MCCB-40AMP HAVELLS RIO",
    itemCode: null,
    subItems: [
      {
        variant: "4",
        dop: "2026-04-27",
        billNumber: null,
        quantity: "4",
        unitRate: 300.0,
        amount: 1200.0,
        receivedQty: "4.0",
        openingStock: "4.0",
        issued: "0.0",
        balance: "4.0",
        avlStockTotal: "4.0",
        dealerName: "M/S NARMADA ENTERPRISES ,SHOP NO B11 RAJGERI APARTMENT GANDHI NAGAR GWALIOR",
        slp: null,
        remarks: null,
      },
    ],
  },
];

// ─────────────────────────────────────────────
// Seed function
// ─────────────────────────────────────────────

async function main() {
  console.log("🔌 Starting Electrical Inventory Seed...\n");

  let itemsCreated = 0;
  let itemsSkipped = 0;
  let subItemsCreated = 0;
  let subItemsSkipped = 0;
  let ordersCreated = 0;

  for (const itemData of electricalData) {
    // ── 1. Upsert parent item (by name) ──────────────────────────────
    const item = await prisma.electrical_items.upsert({
      where: { name: itemData.name },
      update: {
        itemCode: parseString(itemData.itemCode),
      },
      create: {
        name: itemData.name,
        itemCode: parseString(itemData.itemCode),
      },
    });

    const isNewItem = !item.updatedAt || item.updatedAt.getTime() === item.createdAt?.getTime();
    if (isNewItem) {
      itemsCreated++;
      console.log(`  ✅ Item [${item.id}]: ${item.name}`);
    } else {
      itemsSkipped++;
      console.log(`  ⏭️  Item (exists) [${item.id}]: ${item.name}`);
    }

    // ── 2. Upsert sub-items (by itemId + variant) ─────────────────────
    for (const sub of itemData.subItems) {
      const subItem = await prisma.electrical_sub_items.upsert({
        where: {
          itemId_variant: {
            itemId: item.id,
            variant: sub.variant,
          },
        },
        update: {},   // sub-item schema has no extra fields to update
        create: {
          itemId: item.id,
          variant: sub.variant,
        },
      });

      const isNewSubItem = !subItem.updatedAt || subItem.updatedAt?.getTime() === subItem.createdAt?.getTime();
      if (isNewSubItem) {
        subItemsCreated++;
        console.log(`    ✅  SubItem [${subItem.id}]: variant="${sub.variant}"`);
      } else {
        subItemsSkipped++;
        console.log(`    ⏭️   SubItem (exists) [${subItem.id}]: variant="${sub.variant}"`);
      }

      // ── 3. Create order record for this sub-item ──────────────────────
      // We always insert orders (they represent purchase history entries,
      // so duplicates per sub-item are expected if the seed is re-run —
      // guard with a findFirst check on key business fields).
      const dopDate = parseDate(sub.dop);

      const existingOrder = await prisma.electrical_orders.findFirst({
        where: {
          subItemId:  subItem.id,
          dop:        dopDate,
          dealerName: parseString(sub.dealerName),
        },
      });

      if (!existingOrder) {
        await prisma.electrical_orders.create({
          data: {
            subItemId:    subItem.id,
            dop:          dopDate,
            billNumber:   parseString(sub.billNumber),
            quantity:     parseString(sub.quantity),
            unitRate:     parseDecimal(sub.unitRate),
            amount:       parseDecimal(sub.amount),
            receivedQty:  parseString(sub.receivedQty),
            openingStock: parseString(sub.openingStock),
            issued:       parseString(sub.issued),
            balance:      parseString(sub.balance),
            avlStockTotal: parseString(sub.avlStockTotal),
            dealerName:   parseString(sub.dealerName),
            slp:          parseIntVal(sub.slp),
            remarks:      parseString(sub.remarks),
          },
        });
        ordersCreated++;
        console.log(`      📦 Order created for subItem[${subItem.id}] — dop=${sub.dop ?? "null"}`);
      } else {
        console.log(`      ⏭️   Order already exists for subItem[${subItem.id}] — skipping`);
      }

      // ── 4. Populate dynamic InventoryItem table under "Electrical" category ───────────
      const cleanStock = Math.round(
        parseFloat(sub.balance) || parseFloat(sub.quantity) || 0
      );
      const cleanPrice = parseFloat(sub.unitRate) || 0;
      let cleanStatus = "Good";
      if (cleanStock === 0) cleanStatus = "Low";
      else if (cleanStock < 10) cleanStatus = "Medium";

      const existingInventoryItem = await prisma.inventoryItem.findFirst({
        where: {
          item: { equals: item.name, mode: "insensitive" },
          category: { equals: "Electrical", mode: "insensitive" },
          type: { equals: sub.variant, mode: "insensitive" }
        }
      });

      if (!existingInventoryItem) {
        await prisma.inventoryItem.create({
          data: {
            item: item.name,
            category: "Electrical",
            subcategory: item.name,
            type: sub.variant,
            stock: cleanStock,
            price: cleanPrice,
            status: cleanStatus
          }
        });
      } else {
        await prisma.inventoryItem.update({
          where: { id: existingInventoryItem.id },
          data: {
            subcategory: item.name,
            stock: cleanStock,
            price: cleanPrice,
            status: cleanStatus
          }
        });
      }
    }
  }

  // ── Summary ────────────────────────────────────────────────────────
  console.log("\n────────────────────────────────────────────────");
  console.log("✅ Electrical Inventory Seed Complete");
  console.log(`   Items     : ${itemsCreated} created  /  ${itemsSkipped} already existed`);
  console.log(`   Sub-Items : ${subItemsCreated} created  /  ${subItemsSkipped} already existed`);
  console.log(`   Orders    : ${ordersCreated} inserted`);
  console.log("────────────────────────────────────────────────\n");
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
